// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-dtRswH502LSl8btFRNAIIXK1BeG9v7Y',
    appId: '1:989344681643:android:e88d5e931873dd97f1b1ee',
    messagingSenderId: '989344681643',
    projectId: 'we-chat-6b5ae',
    storageBucket: 'we-chat-6b5ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3foqLCXDXFTeA4sLa8onF9sIsYikZeLI',
    appId: '1:989344681643:ios:d2f979e884a055c6f1b1ee',
    messagingSenderId: '989344681643',
    projectId: 'we-chat-6b5ae',
    storageBucket: 'we-chat-6b5ae.appspot.com',
    androidClientId: '989344681643-ic05d5tgl6jo3t8932mrmrt7kk2bgk70.apps.googleusercontent.com',
    iosClientId: '989344681643-rocr0pvbjh2s5cdt59ihri903ma71100.apps.googleusercontent.com',
    iosBundleId: 'com.example.weChat',
  );
}
